
# This file has been generated at Wed Feb 04 13:35:07 2009

from openalea.core import *


__name__ = 'groimp.example'

__editable__ = True
__description__ = 'OpenAlea / GroIMP communication.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr'
__alias__ = []
__version__ = '0.0.1'
__authors__ = 'C. Pradal'
__institutes__ = 'INRIA/CIRAD/University of Cottbus'
__icon__ = ''


__all__ = ['_41266576', '_41266608', '_42399792', '_41266512', '_41266480', '_41266640', '_41266544']


_41266576 = DataFactory(name='axiom.xl',
                    description='GroIMP LSystem',
                    editors=None,
                    includes=None,
                    )



_41266608 = CompositeNodeFactory(name='Simple LSystem',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('groimp', 'http connexion'),
   3: ('groimp', 'simulation'),
   4: ('groimp.example', 'axiom.xl'),
   5: ('groimp.example', 'axiom.xeg'),
   6: ('openalea.data structure.string', 'string'),
   7: ('groimp', 'xml2graph'),
   8: ('openalea.file', 'read'),
   9: ('openalea.data structure.string', 'string'),
   10: ('vplants.plantgl.visualization', 'plot3D'),
   11: ('openalea.file', 'read'),
   12: ('openalea.flow control', 'pool reader'),
   14: ('openalea.flow control', 'pool writer'),
   15: ('openalea.data structure.string', 'string'),
   16: ('openalea.flow control', 'pool writer'),
   17: ('openalea.data structure.string', 'string'),
   18: ('openalea.system', 'vprint'),
   19: ('openalea.system', 'vprint')},
                             elt_connections={  9790572: (2, 0, 3, 3),
   9790584: (12, 0, 3, 1),
   9790596: (11, 0, 3, 0),
   9790608: (14, 0, 19, 0),
   9790620: (8, 0, 14, 1),
   9790632: (3, 0, 16, 1),
   9790644: (15, 0, 12, 0),
   9790656: (17, 0, 16, 0),
   9790668: (16, 0, 18, 0),
   9790680: (4, 0, 11, 0),
   9790692: (9, 0, 3, 2),
   9790704: (7, 1, 10, 0),
   9790716: (16, 0, 7, 0),
   9790728: (5, 0, 8, 0),
   9790740: (6, 0, 14, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'http connexion',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 521.12309968370573,
         'posy': 81.529180695847373,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'simulation',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 340.94543924089379,
         'posy': 161.6878379757168,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'axiom.xl',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 222.5,
         'posy': 36.25,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'axiom.xeg',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -41.25,
         'posy': -1.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': "'graph'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -92.5,
         'posy': 46.25,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 300.79953576165713,
         'posy': 305.08251709009289,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 11.25,
         'posy': 48.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': "'run'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 435.0,
         'posy': 80.0,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 319.79071013161922,
          'posy': 354.87947658402209,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 239.77145189266395,
          'posy': 99.479644934190333,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': "pool ['graph']",
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 318.75,
          'posy': 62.5,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'set pool[graph]',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': -95.0,
          'posy': 127.5,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': "'graph'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 330.0,
          'posy': 0.0,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'set pool[graph]',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 247.5,
          'posy': 248.75,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': "'graph'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 256.25,
          'posy': 187.5,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'vprint',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 413.75,
          'posy': 317.5,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'vprint',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -66.25,
          'posy': 178.75,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(0, "'localhost'"), (1, "'58070'")],
   3: [],
   4: [(0, 'PackageData(groimp.example, axiom.xl)'), (1, 'None'), (2, 'None')],
   5: [  (0, 'PackageData(groimp.example, axiom.xeg)'),
         (1, 'None'),
         (2, 'None')],
   6: [(0, "'graph'")],
   7: [],
   8: [],
   9: [(0, "'run'")],
   10: [],
   11: [],
   12: [],
   14: [],
   15: [(0, "'graph'")],
   16: [],
   17: [(0, "'graph'")],
   18: [(1, "'graph'"), (2, 'False'), (3, "<type 'str'>")],
   19: [(1, "'graph'"), (2, 'False'), (3, "<type 'str'>")],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




_42399792 = CompositeNodeFactory(name='test for',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  13: ('openalea.file', 'read'),
   18: ('openalea.flow control', 'for'),
   20: ('groimp.example', 'axiom.xeg'),
   21: ('groimp', 'http connexion'),
   22: ('groimp', 'simulation'),
   23: ('groimp.example', 'axiom.xl'),
   24: ('openalea.data structure.string', 'string'),
   25: ('openalea.file', 'read'),
   26: ('openalea.python method', 'range'),
   27: ('openalea.flow control', 'X'),
   28: ('vplants.plantgl.visualization', 'plot3D'),
   29: ('groimp', 'xml2graph')},
                             elt_connections={  9790492: (18, 0, 29, 0),
   9790504: (29, 1, 28, 0),
   9790516: (26, 0, 18, 1),
   9790528: (23, 0, 25, 0),
   9790540: (22, 0, 18, 2),
   9790552: (21, 0, 22, 3),
   9790564: (27, 0, 22, 1),
   9790576: (24, 0, 22, 2),
   9790588: (25, 0, 22, 0),
   9790600: (13, 0, 18, 0),
   9790720: (20, 0, 13, 0)},
                             elt_data={  13: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': -82.466329966329965,
          'posy': 324.99298540965202,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'for',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 22.167508417508415,
          'posy': 370.65796857463533,
          'priority': 0,
          'user_application': None},
   20: {  'block': False,
          'caption': 'axiom.xeg',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': -113.69668911335579,
          'posy': 266.44921436588106,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'http connexion',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 217.45230078563412,
          'posy': 227.2727272727272,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'simulation',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 103.81593714927047,
          'posy': 315.65656565656587,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': 'axiom.xl',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 30.864197530864196,
          'posy': 207.63187429854099,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': "'run'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 150.11223344556669,
          'posy': 242.70482603815935,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 12.626262626262644,
          'posy': 252.52525252525251,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'range',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -1.4029180695847323,
          'posy': 312.85072951739619,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': 'X0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 91.189674523007824,
          'posy': 152.91806958473623,
          'priority': 0,
          'user_application': None},
   28: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 8.417508417508401,
          'posy': 502.24466891133551,
          'priority': 0,
          'user_application': None},
   29: {  'block': False,
          'caption': 'xml2graph',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -1.4210854715202004e-014,
          'posy': 436.30751964085289,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  13: [],
   18: [],
   20: [  (0, 'PackageData(groimp.example, axiom.xeg)'),
          (1, 'None'),
          (2, 'None')],
   21: [(0, "'localhost'"), (1, "'58070'")],
   22: [],
   23: [  (0, 'PackageData(groimp.example, axiom.xl)'),
          (1, 'None'),
          (2, 'None')],
   24: [(0, "'run'")],
   25: [],
   26: [(0, '0'), (1, '6'), (2, '1')],
   27: [(0, "'x'")],
   28: [],
   29: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )



_41266512 = DataFactory(name='graph1.xml',
                    description='XML graph description',
                    editors=None,
                    includes=None,
                    )


_41266480 = DataFactory(name='axiom.xeg',
                    description='GroIMP axiom',
                    editors=None,
                    includes=None,
                    )


_41266640 = DataFactory(name='code1.xl',
                    description='XL code used in the 1st example.',
                    editors=None,
                    includes=None,
                    )



_41266544 = CompositeNodeFactory(name='1. Simple Tree',
                             description='',
                             category='composite',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('groimp', 'http connexion'),
   3: ('groimp', 'simulation'),
   4: ('groimp.example', 'code1.xl'),
   5: ('groimp.example', 'graph1.xml'),
   6: ('groimp', 'xml2graph'),
   7: ('groimp', 'xml2graph'),
   8: ('vplants.plantgl.visualization', 'plot3D'),
   9: ('openalea.data structure.string', 'string'),
   10: ('vplants.plantgl.visualization', 'plot3D'),
   11: ('openalea.file', 'read'),
   12: ('openalea.file', 'read'),
   13: ('openalea.file', 'read'),
   14: ('groimp.example', 'graph1.xml')},
                             elt_connections={  9793244: (13, 0, 6, 0),
   9793256: (14, 0, 13, 0),
   9793268: (6, 1, 8, 0),
   9793280: (7, 1, 10, 0),
   9793292: (11, 0, 3, 0),
   9793304: (3, 0, 7, 0),
   9793316: (2, 0, 3, 3),
   9793328: (12, 0, 3, 1),
   9793340: (5, 0, 12, 0),
   9793352: (4, 0, 11, 0),
   9793364: (9, 0, 3, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'http connexion',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 521.12309968370573,
         'posy': 81.529180695847373,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'simulation',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 340.94543924089379,
         'posy': 161.6878379757168,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'code1.xl',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 229.56841138659291,
         'posy': 48.464442403836358,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'graph1.xml',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 326.49729619426603,
         'posy': 44.638302214059792,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 88.75,
         'posy': 222.5,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 340.79953576165707,
         'posy': 211.33251709009289,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'plot3D',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 118.75,
         'posy': 302.5,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': "'run'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 435.0,
         'posy': 80.0,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 372.29071013161922,
          'posy': 261.12947658402203,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 239.77145189266395,
          'posy': 99.479644934190333,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 348.17875726966628,
          'posy': 110.95806550352,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 95.0,
          'posy': 116.25,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'graph1.xml',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 71.25,
          'posy': 40.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(0, "'localhost'"), (1, "'58070'")],
   3: [],
   4: [(0, 'PackageData(groimp.example, code1.xl)'), (1, 'None'), (2, 'None')],
   5: [  (0, 'PackageData(groimp.example, graph1.xml)'),
         (1, 'None'),
         (2, 'None')],
   6: [],
   7: [],
   8: [],
   9: [(0, "'run'")],
   10: [],
   11: [],
   12: [],
   13: [],
   14: [  (0, 'PackageData(groimp.example, graph1.xml)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




