
# This file has been generated at Mon Nov 23 16:47:37 2009

from openalea.core import *


__name__ = 'groimp.example'

__editable__ = True
__description__ = 'OpenAlea / GroIMP communication.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr'
__alias__ = []
__version__ = '0.0.1'
__authors__ = 'C. Pradal'
__institutes__ = 'INRIA/CIRAD/University of Cottbus'
__icon__ = ''


__all__ = ['_75725680', '_75725776', '_75725936', '_75725744', '_75725840', '_75725904', '_75725648', '_75725968', '_75725808', '_75725872', '_75725712']



_75725680 = CompositeNodeFactory(name='Simple LSystem',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('groimp', 'http connexion'),
   3: ('groimp', 'simulation'),
   4: ('groimp.example', 'axiom.xl'),
   5: ('groimp.example', 'axiom.xeg'),
   6: ('openalea.data structure.string', 'string'),
   7: ('groimp', 'xml2graph'),
   8: ('openalea.file', 'read'),
   9: ('openalea.data structure.string', 'string'),
   10: ('vplants.plantgl.visualization', 'plot3D'),
   11: ('openalea.file', 'read'),
   12: ('openalea.flow control', 'pool reader'),
   14: ('openalea.flow control', 'pool writer'),
   15: ('openalea.data structure.string', 'string'),
   16: ('openalea.flow control', 'pool writer'),
   17: ('openalea.data structure.string', 'string'),
   18: ('openalea.system', 'vprint'),
   19: ('openalea.system', 'vprint')},
                             elt_connections={  9790572: (2, 0, 3, 3),
   9790584: (12, 0, 3, 1),
   9790596: (11, 0, 3, 0),
   9790608: (14, 0, 19, 0),
   9790620: (8, 0, 14, 1),
   9790632: (3, 0, 16, 1),
   9790644: (15, 0, 12, 0),
   9790656: (17, 0, 16, 0),
   9790668: (16, 0, 18, 0),
   9790680: (4, 0, 11, 0),
   9790692: (9, 0, 3, 2),
   9790704: (7, 1, 10, 0),
   9790716: (16, 0, 7, 0),
   9790728: (5, 0, 8, 0),
   9790740: (6, 0, 14, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'http connexion',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 521.12309968370573,
         'posy': 81.529180695847373,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'simulation',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 340.94543924089379,
         'posy': 161.6878379757168,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'axiom.xl',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 222.5,
         'posy': 36.25,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'axiom.xeg',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': -41.25,
         'posy': -1.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': "'graph'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -92.5,
         'posy': 46.25,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 300.79953576165713,
         'posy': 305.08251709009289,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'read',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 11.25,
         'posy': 48.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': "'run'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 435.0,
         'posy': 80.0,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 319.79071013161922,
          'posy': 354.87947658402209,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 239.77145189266395,
          'posy': 99.479644934190333,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': "pool ['graph']",
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 318.75,
          'posy': 62.5,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'set pool[graph]',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': -95.0,
          'posy': 127.5,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': "'graph'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 330.0,
          'posy': 0.0,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'set pool[graph]',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 247.5,
          'posy': 248.75,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': "'graph'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 256.25,
          'posy': 187.5,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'vprint',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 413.75,
          'posy': 317.5,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'vprint',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -66.25,
          'posy': 178.75,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(0, "'localhost'"), (1, "'58070'")],
   3: [],
   4: [(0, 'PackageData(groimp.example, axiom.xl)'), (1, 'None'), (2, 'None')],
   5: [  (0, 'PackageData(groimp.example, axiom.xeg)'),
         (1, 'None'),
         (2, 'None')],
   6: [(0, "'graph'")],
   7: [],
   8: [],
   9: [(0, "'run'")],
   10: [],
   11: [],
   12: [],
   14: [],
   15: [(0, "'graph'")],
   16: [],
   17: [(0, "'graph'")],
   18: [(1, "'graph'"), (2, 'False'), (3, "<type 'str'>")],
   19: [(1, "'graph'"), (2, 'False'), (3, "<type 'str'>")],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




_75725776 = CompositeNodeFactory(name='2. LSystem in a loop',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  13: ('openalea.file', 'read'),
   16: ('groimp', 'xml2graph'),
   17: ('vplants.plantgl.visualization', 'plot3D'),
   18: ('openalea.flow control', 'for'),
   19: ('openalea.flow control', 'rendez vous'),
   20: ('groimp.example', 'axiom.xeg'),
   21: ('groimp', 'http connexion'),
   22: ('groimp', 'simulation'),
   23: ('groimp.example', 'axiom.xl'),
   24: ('openalea.data structure.string', 'string'),
   25: ('openalea.file', 'read'),
   26: ('openalea.python method', 'range'),
   27: ('openalea.flow control', 'X')},
                             elt_connections={  9925900: (22, 0, 16, 0),
   9925912: (17, 0, 19, 1),
   9925924: (16, 1, 17, 0),
   9925936: (19, 0, 18, 2),
   9925948: (25, 0, 22, 0),
   9925960: (26, 0, 18, 1),
   9925972: (24, 0, 22, 2),
   9925996: (27, 0, 22, 1),
   9926020: (21, 0, 22, 3),
   9926032: (22, 0, 19, 0),
   9926044: (13, 0, 18, 0),
   9926056: (20, 0, 13, 0),
   9926068: (23, 0, 25, 0)},
                             elt_data={  13: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': -82.466329966329965,
          'posy': 324.99298540965202,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'xml2graph',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 391.25,
          'posy': 340.0,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 412.16750841750843,
          'posy': 419.68714927048268,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'for',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 22.167508417508415,
          'posy': 555.65796857463533,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'rendez vous',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 213.75,
          'posy': 398.75,
          'priority': 0,
          'user_application': None},
   20: {  'block': False,
          'caption': 'axiom.xeg',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': -113.69668911335579,
          'posy': 266.44921436588106,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'http connexion',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 218.70230078563412,
          'posy': 227.2727272727272,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'simulation',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 103.81593714927047,
          'posy': 315.65656565656587,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': 'axiom.xl',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 30.864197530864203,
          'posy': 208.88187429854099,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': "'run'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 150.11223344556669,
          'posy': 242.70482603815935,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 12.626262626262644,
          'posy': 252.52525252525251,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'range',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -0.15291806958472876,
          'posy': 414.10072951739619,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': 'X0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 103.68967452300782,
          'posy': 129.16806958473626,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  13: [],
   16: [],
   17: [],
   18: [],
   19: [],
   20: [  (0, 'PackageData(groimp.example, axiom.xeg)'),
          (1, 'None'),
          (2, 'None')],
   21: [(0, "'localhost'"), (1, "'58070'")],
   22: [],
   23: [  (0, 'PackageData(groimp.example, axiom.xl)'),
          (1, 'None'),
          (2, 'None')],
   24: [(0, "'run'")],
   25: [],
   26: [(0, '0'), (1, '6'), (2, '1')],
   27: [(0, "'x'")],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )



_75725936 = DataFactory(name='axiom.xeg',
                    description='GroIMP axiom',
                    editors=None,
                    includes=None,
                    )



_75725744 = CompositeNodeFactory(name='1. Simple Tree',
                             description='',
                             category='composite',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('groimp', 'http connexion'),
   3: ('groimp', 'simulation'),
   4: ('groimp.example', 'code1.xl'),
   5: ('groimp.example', 'graph1.xml'),
   6: ('groimp', 'xml2graph'),
   7: ('groimp', 'xml2graph'),
   8: ('vplants.plantgl.visualization', 'plot3D'),
   9: ('openalea.data structure.string', 'string'),
   10: ('vplants.plantgl.visualization', 'plot3D'),
   11: ('openalea.file', 'read'),
   12: ('openalea.file', 'read'),
   13: ('openalea.file', 'read'),
   14: ('groimp.example', 'graph1.xml')},
                             elt_connections={  9793244: (13, 0, 6, 0),
   9793256: (14, 0, 13, 0),
   9793268: (6, 1, 8, 0),
   9793280: (7, 1, 10, 0),
   9793292: (11, 0, 3, 0),
   9793304: (3, 0, 7, 0),
   9793316: (2, 0, 3, 3),
   9793328: (12, 0, 3, 1),
   9793340: (5, 0, 12, 0),
   9793352: (4, 0, 11, 0),
   9793364: (9, 0, 3, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'http connexion',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 521.12309968370573,
         'posy': 81.529180695847373,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'simulation',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 340.94543924089379,
         'posy': 161.6878379757168,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'code1.xl',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 229.56841138659291,
         'posy': 48.464442403836358,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'graph1.xml',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 326.49729619426603,
         'posy': 44.638302214059792,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 88.75,
         'posy': 222.5,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'xml2graph',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 340.79953576165707,
         'posy': 211.33251709009289,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'plot3D',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 118.75,
         'posy': 302.5,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': "'run'",
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 435.0,
         'posy': 80.0,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 372.29071013161922,
          'posy': 261.12947658402203,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 239.77145189266395,
          'posy': 99.479644934190333,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 348.17875726966628,
          'posy': 110.95806550352,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 95.0,
          'posy': 116.25,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'graph1.xml',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 71.25,
          'posy': 40.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [(0, "'localhost'"), (1, "'58070'")],
   3: [],
   4: [(0, 'PackageData(groimp.example, code1.xl)'), (1, 'None'), (2, 'None')],
   5: [  (0, 'PackageData(groimp.example, graph1.xml)'),
         (1, 'None'),
         (2, 'None')],
   6: [],
   7: [],
   8: [],
   9: [(0, "'run'")],
   10: [],
   11: [],
   12: [],
   13: [],
   14: [  (0, 'PackageData(groimp.example, graph1.xml)'),
          (1, 'None'),
          (2, 'None')],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )



_75725840 = DataFactory(name='beech.rgg',
                    description='',
                    editors=None,
                    includes=None,
                    )


_75725904 = DataFactory(name='code1.xl',
                    description='XL code used in the 1st example.',
                    editors=None,
                    includes=None,
                    )



_75725648 = CompositeNodeFactory(name='3. Beech model with light',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  12: ('openalea.file', 'write'),
   13: ('openalea.file', 'read'),
   14: ('vplants.plantgl.visualization', 'plot3D'),
   15: ('groimp.example', 'beech.rgg'),
   16: ('groimp', 'xml2graph'),
   17: ('vplants.plantgl.visualization', 'plot3D'),
   18: ('openalea.flow control', 'for'),
   19: ('openalea.flow control', 'rendez vous'),
   20: ('groimp.example', 'beech.xeg'),
   21: ('groimp', 'http connexion'),
   22: ('groimp', 'simulation'),
   23: ('groimp', 'xml2graph'),
   24: ('openalea.data structure.string', 'string'),
   25: ('openalea.file', 'read'),
   26: ('openalea.python method', 'range'),
   27: ('openalea.flow control', 'X')},
                             elt_connections={  9927444: (18, 0, 12, 0),
   9927456: (21, 0, 22, 3),
   9927468: (15, 0, 25, 0),
   9927480: (13, 0, 18, 0),
   9927492: (26, 0, 18, 1),
   9927504: (25, 0, 22, 0),
   9927516: (16, 1, 17, 0),
   9927528: (22, 0, 16, 0),
   9927540: (18, 0, 23, 0),
   9927552: (20, 0, 13, 0),
   9927564: (23, 1, 14, 0),
   9927576: (27, 0, 22, 1),
   9927588: (24, 0, 22, 2),
   9927600: (22, 0, 18, 2),
   9927612: (17, 0, 19, 1)},
                             elt_data={  12: {  'block': False,
          'caption': 'write',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 21.25,
          'posy': 658.75,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': -82.466329966329965,
          'posy': 324.99298540965202,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 360.0,
          'posy': 588.75,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': 'beech.rgg',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': -18.75,
          'posy': 170.0,
          'priority': 0,
          'user_application': None},
   16: {  'block': False,
          'caption': 'xml2graph',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 391.25,
          'posy': 340.0,
          'priority': 0,
          'user_application': None},
   17: {  'block': False,
          'caption': 'plot3D',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 412.16750841750843,
          'posy': 419.68714927048268,
          'priority': 0,
          'user_application': None},
   18: {  'block': False,
          'caption': 'for',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 22.167508417508415,
          'posy': 555.65796857463533,
          'priority': 0,
          'user_application': None},
   19: {  'block': False,
          'caption': 'rendez vous',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 213.75,
          'posy': 398.75,
          'priority': 0,
          'user_application': None},
   20: {  'block': False,
          'caption': 'beech.xeg',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': -95.0,
          'posy': 243.75,
          'priority': 0,
          'user_application': None},
   21: {  'block': False,
          'caption': 'http connexion',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 218.70230078563412,
          'posy': 227.2727272727272,
          'priority': 0,
          'user_application': None},
   22: {  'block': False,
          'caption': 'simulation',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 103.81593714927047,
          'posy': 315.65656565656587,
          'priority': 0,
          'user_application': None},
   23: {  'block': False,
          'caption': 'xml2graph',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 228.75,
          'posy': 517.5,
          'priority': 0,
          'user_application': None},
   24: {  'block': False,
          'caption': "'init;100step'",
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 150.11223344556669,
          'posy': 242.70482603815935,
          'priority': 0,
          'user_application': None},
   25: {  'block': False,
          'caption': 'read',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set(),
          'posx': 12.626262626262644,
          'posy': 252.52525252525251,
          'priority': 0,
          'user_application': None},
   26: {  'block': False,
          'caption': 'range',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -0.15291806958472876,
          'posy': 414.10072951739619,
          'priority': 0,
          'user_application': None},
   27: {  'block': False,
          'caption': 'X0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 103.68967452300782,
          'posy': 129.16806958473626,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  12: [  (  1,
             "'D:/Documents/pradal/devlp/aleapkg/groimp/groimp/example/beech_run100.xeg'"),
          (2, "'w'")],
   13: [],
   14: [],
   15: [  (0, 'PackageData(groimp.example, beech.rgg)'),
          (1, 'None'),
          (2, 'None')],
   16: [],
   17: [],
   18: [],
   19: [  (  0,
             '\'<graph>\\r\\n  <root root_id="1"/>\\r\\n  <type name="Internode">\\r\\n    <extends name="Organ"/>\\r\\n  </type>\\r\\n  <type name="Organ">\\r\\n    <extends name="Cylinder"/>\\r\\n    <property name="order" type="int"/>\\r\\n    <property name="allocatedCarbon" type="float"/>\\r\\n    <property name="producedCarbon" type="float"/>\\r\\n    <property name="exportedCarbon" type="float"/>\\r\\n    <property name="preference" type="float"/>\\r\\n  </type>\\r\\n  <node id="2" name="" type="Internode">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.019357322"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.0 0.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n  </node>\\r\\n  <edge id="1" src_id="18" dest_id="2" type="successor"/>\\r\\n  <node id="3" name="" type="RL">\\r\\n    <property name="angle" value="-90.0"/>\\r\\n  </node>\\r\\n  <edge id="2" src_id="42" dest_id="3" type="successor"/>\\r\\n  <node id="4" name="" type="Internode">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.006316352"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.0 0.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n  </node>\\r\\n  <edge id="3" src_id="26" dest_id="4" type="successor"/>\\r\\n  <node id="5" name="" type="RL">\\r\\n    <property name="angle" value="90.0"/>\\r\\n  </node>\\r\\n  <edge id="4" src_id="20" dest_id="5" type="branch"/>\\r\\n  <node id="6" name="" type="RL">\\r\\n    <property name="angle" value="90.0"/>\\r\\n  </node>\\r\\n  <edge id="5" src_id="10" dest_id="6" type="branch"/>\\r\\n  <node id="7" name="" type="Internode">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.02600235"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.0 0.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n  </node>\\r\\n  <edge id="6" src_id="19" dest_id="7" type="successor"/>\\r\\n  <node id="8" name="" type="RL">\\r\\n    <property name="angle" value="-90.0"/>\\r\\n  </node>\\r\\n  <edge id="7" src_id="14" dest_id="8" type="successor"/>\\r\\n  <node id="9" name="" type="Internode">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.024841484"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.0 0.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n  </node>\\r\\n  <edge id="8" src_id="13" dest_id="9" type="successor"/>\\r\\n  <node id="10" name="" type="AdjustLU"/>\\r\\n  <edge id="9" src_id="33" dest_id="10" type="successor"/>\\r\\n  <node id="11" name="" type="RU">\\r\\n    <property name="angle" value="2.979721"/>\\r\\n  </node>\\r\\n  <edge id="10" src_id="9" dest_id="11" type="successor"/>\\r\\n  <type name="BeechLeaf">\\r\\n    <extends name="Parallelogram"/>\\r\\n    <property name="producedCarbon" type="float"/>\\r\\n  </type>\\r\\n  <type name="Parallelogram">\\r\\n    <extends name="Axis"/>\\r\\n  </type>\\r\\n  <type name="Axis">\\r\\n    <extends name="AxisBase"/>\\r\\n    <property name="length" type="float"/>\\r\\n    <property name="startPosition" type="float"/>\\r\\n    <property name="endPosition" type="float"/>\\r\\n  </type>\\r\\n  <type name="AxisBase">\\r\\n    <extends name="Node"/>\\r\\n    <property name="scaleV" type="boolean"/>\\r\\n  </type>\\r\\n  <node id="12" name="" type="BeechLeaf">\\r\\n    <property name="color">\\r\\n      <rgb>0.0 1.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="scaleV" value="false"/>\\r\\n    <property name="length" value="0.05856896"/>\\r\\n    <property name="startPosition" value="0.0"/>\\r\\n    <property name="endPosition" value="1.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="11" src_id="28" dest_id="12" type="successor"/>\\r\\n  <node id="13" name="" type="RH">\\r\\n    <property name="angle" value="-10.055634"/>\\r\\n  </node>\\r\\n  <edge id="12" src_id="24" dest_id="13" type="successor"/>\\r\\n  <type name="RD">\\r\\n    <extends name="Tropism"/>\\r\\n  </type>\\r\\n  <type name="Tropism">\\r\\n    <extends name="Node"/>\\r\\n    <property name="strength" type="bounded"/>\\r\\n  </type>\\r\\n  <node id="14" name="" type="RD"/>\\r\\n  <edge id="13" src_id="5" dest_id="14" type="successor"/>\\r\\n  <type name="Bud">\\r\\n    <extends name="Node"/>\\r\\n    <property name="order" type="int"/>\\r\\n    <property name="vitality" type="float"/>\\r\\n    <property name="sign" type="int"/>\\r\\n  </type>\\r\\n  <node id="15" name="" type="Bud">\\r\\n    <property name="order" value="1"/>\\r\\n    <property name="vitality" value="2.0"/>\\r\\n    <property name="sign" value="-1"/>\\r\\n  </node>\\r\\n  <edge id="14" src_id="10" dest_id="15" type="successor"/>\\r\\n  <node id="16" name="" type="BeechLeaf">\\r\\n    <property name="color">\\r\\n      <rgb>0.0 1.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="scaleV" value="false"/>\\r\\n    <property name="length" value="0.051693276"/>\\r\\n    <property name="startPosition" value="0.0"/>\\r\\n    <property name="endPosition" value="1.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="15" src_id="41" dest_id="16" type="successor"/>\\r\\n  <node id="17" name="" type="Internode">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.018256005"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.0 0.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n  </node>\\r\\n  <edge id="16" src_id="22" dest_id="17" type="successor"/>\\r\\n  <node id="18" name="" type="RH">\\r\\n    <property name="angle" value="-28.31593"/>\\r\\n  </node>\\r\\n  <edge id="17" src_id="31" dest_id="18" type="successor"/>\\r\\n  <node id="19" name="" type="RH">\\r\\n    <property name="angle" value="33.89712"/>\\r\\n  </node>\\r\\n  <edge id="18" src_id="11" dest_id="19" type="successor"/>\\r\\n  <node id="20" name="" type="AdjustLU"/>\\r\\n  <edge id="19" src_id="47" dest_id="20" type="successor"/>\\r\\n  <node id="21" name="" type="RD"/>\\r\\n  <edge id="20" src_id="6" dest_id="21" type="successor"/>\\r\\n  <node id="22" name="" type="RH">\\r\\n    <property name="angle" value="26.3332"/>\\r\\n  </node>\\r\\n  <edge id="21" src_id="36" dest_id="22" type="successor"/>\\r\\n  <node id="23" name="" type="BeechLeaf">\\r\\n    <property name="color">\\r\\n      <rgb>0.0 1.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="scaleV" value="false"/>\\r\\n    <property name="length" value="0.072525814"/>\\r\\n    <property name="startPosition" value="0.0"/>\\r\\n    <property name="endPosition" value="1.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="22" src_id="8" dest_id="23" type="successor"/>\\r\\n  <node id="24" name="" type="RU">\\r\\n    <property name="angle" value="-11.236376"/>\\r\\n  </node>\\r\\n  <edge id="23" src_id="17" dest_id="24" type="successor"/>\\r\\n  <node id="25" name="" type="RL">\\r\\n    <property name="angle" value="63.975754"/>\\r\\n  </node>\\r\\n  <edge id="24" src_id="18" dest_id="25" type="branch"/>\\r\\n  <type name="Beech">\\r\\n    <extends name="Organ"/>\\r\\n    <property name="totalMass" type="float"/>\\r\\n    <property name="produced" type="float"/>\\r\\n  </type>\\r\\n  <node id="26" name="" type="Beech">\\r\\n    <property name="radius" value="1.0E-4"/>\\r\\n    <property name="height" value="0.01"/>\\r\\n    <property name="top_open" value="false"/>\\r\\n    <property name="bottom_open" value="false"/>\\r\\n    <property name="color">\\r\\n      <rgb>0.6666667 0.33333334 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="allocatedCarbon" value="0.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n    <property name="exportedCarbon" value="0.0"/>\\r\\n    <property name="preference" value="1.0"/>\\r\\n    <property name="totalMass" value="3.6442472E-7"/>\\r\\n    <property name="produced" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="25" src_id="1" dest_id="26" type="successor"/>\\r\\n  <node id="27" name="" type="RD"/>\\r\\n  <edge id="26" src_id="32" dest_id="27" type="successor"/>\\r\\n  <node id="28" name="" type="RL">\\r\\n    <property name="angle" value="-90.0"/>\\r\\n  </node>\\r\\n  <edge id="27" src_id="27" dest_id="28" type="successor"/>\\r\\n  <node id="29" name="" type="RH">\\r\\n    <property name="angle" value="24.566957"/>\\r\\n  </node>\\r\\n  <edge id="28" src_id="44" dest_id="29" type="successor"/>\\r\\n  <node id="30" name="" type="Bud">\\r\\n    <property name="order" value="0"/>\\r\\n    <property name="vitality" value="4.5"/>\\r\\n    <property name="sign" value="-1"/>\\r\\n  </node>\\r\\n  <edge id="29" src_id="37" dest_id="30" type="successor"/>\\r\\n  <node id="31" name="" type="RU">\\r\\n    <property name="angle" value="-0.12433431"/>\\r\\n  </node>\\r\\n  <edge id="30" src_id="7" dest_id="31" type="successor"/>\\r\\n  <node id="32" name="" type="RL">\\r\\n    <property name="angle" value="90.0"/>\\r\\n  </node>\\r\\n  <edge id="31" src_id="39" dest_id="32" type="branch"/>\\r\\n  <node id="33" name="" type="RL">\\r\\n    <property name="angle" value="-65.6131"/>\\r\\n  </node>\\r\\n  <edge id="32" src_id="19" dest_id="33" type="branch"/>\\r\\n  <node id="34" name="" type="RL">\\r\\n    <property name="angle" value="75.6615"/>\\r\\n  </node>\\r\\n  <edge id="33" src_id="13" dest_id="34" type="branch"/>\\r\\n  <node id="35" name="" type="RL">\\r\\n    <property name="angle" value="90.0"/>\\r\\n  </node>\\r\\n  <edge id="34" src_id="40" dest_id="35" type="branch"/>\\r\\n  <node id="36" name="" type="RU">\\r\\n    <property name="angle" value="0.31385309"/>\\r\\n  </node>\\r\\n  <edge id="35" src_id="4" dest_id="36" type="successor"/>\\r\\n  <node id="37" name="" type="RD"/>\\r\\n  <edge id="36" src_id="29" dest_id="37" type="successor"/>\\r\\n  <node id="38" name="" type="BeechLeaf">\\r\\n    <property name="color">\\r\\n      <rgb>0.0 1.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="scaleV" value="false"/>\\r\\n    <property name="length" value="0.070333846"/>\\r\\n    <property name="startPosition" value="0.0"/>\\r\\n    <property name="endPosition" value="1.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="37" src_id="49" dest_id="38" type="successor"/>\\r\\n  <node id="39" name="" type="AdjustLU"/>\\r\\n  <edge id="38" src_id="25" dest_id="39" type="successor"/>\\r\\n  <node id="40" name="" type="AdjustLU"/>\\r\\n  <edge id="39" src_id="34" dest_id="40" type="successor"/>\\r\\n  <node id="41" name="" type="RL">\\r\\n    <property name="angle" value="-90.0"/>\\r\\n  </node>\\r\\n  <edge id="40" src_id="21" dest_id="41" type="successor"/>\\r\\n  <node id="42" name="" type="RD"/>\\r\\n  <edge id="41" src_id="48" dest_id="42" type="successor"/>\\r\\n  <node id="43" name="" type="Bud">\\r\\n    <property name="order" value="1"/>\\r\\n    <property name="vitality" value="2.4406781"/>\\r\\n    <property name="sign" value="1"/>\\r\\n  </node>\\r\\n  <edge id="42" src_id="39" dest_id="43" type="successor"/>\\r\\n  <node id="44" name="" type="RU">\\r\\n    <property name="angle" value="2.5810952"/>\\r\\n  </node>\\r\\n  <edge id="43" src_id="2" dest_id="44" type="successor"/>\\r\\n  <node id="45" name="" type="BeechLeaf">\\r\\n    <property name="color">\\r\\n      <rgb>0.0 1.0 0.0</rgb>\\r\\n    </property>\\r\\n    <property name="scaleV" value="false"/>\\r\\n    <property name="length" value="0.04803268"/>\\r\\n    <property name="startPosition" value="0.0"/>\\r\\n    <property name="endPosition" value="1.0"/>\\r\\n    <property name="producedCarbon" value="0.0"/>\\r\\n  </node>\\r\\n  <edge id="44" src_id="3" dest_id="45" type="successor"/>\\r\\n  <node id="46" name="" type="RD"/>\\r\\n  <edge id="45" src_id="35" dest_id="46" type="successor"/>\\r\\n  <node id="47" name="" type="RL">\\r\\n    <property name="angle" value="-49.622982"/>\\r\\n  </node>\\r\\n  <edge id="46" src_id="22" dest_id="47" type="branch"/>\\r\\n  <node id="48" name="" type="RL">\\r\\n    <property name="angle" value="90.0"/>\\r\\n  </node>\\r\\n  <edge id="47" src_id="37" dest_id="48" type="branch"/>\\r\\n  <node id="49" name="" type="RL">\\r\\n    <property name="angle" value="-90.0"/>\\r\\n  </node>\\r\\n  <edge id="48" src_id="46" dest_id="49" type="successor"/>\\r\\n</graph>\'')],
   20: [  (0, 'PackageData(groimp.example, beech.xeg)'),
          (1, 'None'),
          (2, 'None')],
   21: [(0, "'localhost'"), (1, "'58070'")],
   22: [],
   23: [],
   24: [(0, "'init;100step'")],
   25: [],
   26: [(0, '0'), (1, '1'), (2, '1')],
   27: [(0, "'x'")],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )



_75725968 = DataFactory(name='beech.xeg',
                    description='Beech Tree Axiom',
                    editors=None,
                    includes=None,
                    )


_75725808 = DataFactory(name='graph1.xml',
                    description='XML graph description',
                    editors=None,
                    includes=None,
                    )


_75725872 = DataFactory(name='beech.xl',
                    description='XL code for beech tree with light interception and carbon allocation',
                    editors=None,
                    includes=None,
                    )


_75725712 = DataFactory(name='axiom.xl',
                    description='GroIMP LSystem',
                    editors=None,
                    includes=None,
                    )



